# Generated by Django 3.2.3 on 2021-05-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('personal_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_stream', models.CharField(max_length=50)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('has_recieved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_category', models.CharField(max_length=50)),
                ('payment_account', models.CharField(default='Starling (Joint)', max_length=50)),
                ('payment_owner', models.CharField(default='Household', max_length=50)),
                ('payment_date', models.IntegerField()),
                ('instalment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_recipient', models.CharField(max_length=50)),
                ('has_paid', models.BooleanField(default=False)),
                ('payment_completion_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
