# Generated by Django 3.1.7 on 2021-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_stream', models.CharField(max_length=50)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
