# Generated by Django 3.2.4 on 2021-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
