# Generated by Django 3.2 on 2021-04-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0002_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='has_recieved',
            field=models.BooleanField(default=True),
        ),
    ]
