# Generated by Django 3.2.4 on 2021-06-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0002_payment_payment_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_note',
        ),
    ]
