# Generated by Django 3.2.3 on 2021-05-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0003_income_has_recieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('personal_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
        ),
    ]
